apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pytorchcnn-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-02-22T12:24:18.314761',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "pytorchcnn"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0}
spec:
  entrypoint: pytorchcnn
  templates:
  - name: preprocessimagedata
    container:
      args: [--input_data, '', --output_data, /tmp/outputs/output_data/data]
      command: [python, /component/entry_point.py]
      image: jagadeeshj/data_prep_step:22-02-2021-12-23-59.762171
    outputs:
      artifacts:
      - {name: preprocessimagedata-output_data, path: /tmp/outputs/output_data/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Prepare
          data for PyTorch training.\n", "implementation": {"container": {"args":
          ["--input_data", {"inputValue": "input_data"}, "--output_data", {"outputPath":
          "output_data"}], "command": ["python", "/component/entry_point.py"], "image":
          "jagadeeshj/data_prep_step:22-02-2021-12-23-59.762171"}}, "inputs": [{"description":
          "The gcs path to the input dataset", "name": "input_data", "type": "Dataset"}],
          "name": "PreProcessImageData", "outputs": [{"description": "Output data
          GCS location", "name": "output_data", "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "5e4d91e385306a17756df14635151dd0950dc3b748d2bedba157dfaae0ec3427", "url":
          "data_prep_step/resnet/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"input_data":
          ""}'}
  - name: pytorchcnn
    dag:
      tasks:
      - {name: preprocessimagedata, template: preprocessimagedata}
      - name: train-pytorch-cnn
        template: train-pytorch-cnn
        dependencies: [preprocessimagedata]
        arguments:
          artifacts:
          - {name: preprocessimagedata-output_data, from: '{{tasks.preprocessimagedata.outputs.artifacts.preprocessimagedata-output_data}}'}
  - name: train-pytorch-cnn
    container:
      args: [--train_glob, /tmp/inputs/TrainingData/data, --model_save_path, /tmp/outputs/ModelCheckpoint/data,
        --tensorboard_root, /tmp/outputs/TensorboardRoot/data, --max_epochs, '1',
        --gpus, '1', --train_batch_size, None, --val_batch_size, None, --train_num_workers,
        '4', --val_num_workers, '4', --learning_rate, '0.001', --accelerator, None]
      command: [python, /component/entry_point.py]
      image: jagadeeshj/training_step:22-02-2021-12-23-59.762171
      resources:
        limits: {cpu: '4', memory: 14Gi}
    inputs:
      artifacts:
      - {name: preprocessimagedata-output_data, path: /tmp/inputs/TrainingData/data}
    outputs:
      artifacts:
      - {name: train-pytorch-cnn-ModelCheckpoint, path: /tmp/outputs/ModelCheckpoint/data}
      - {name: train-pytorch-cnn-TensorboardRoot, path: /tmp/outputs/TensorboardRoot/data}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Train
          PyTorch ImageNet CNN", "implementation": {"container": {"args": ["--train_glob",
          {"inputPath": "TrainingData"}, "--model_save_path", {"outputPath": "ModelCheckpoint"},
          "--tensorboard_root", {"outputPath": "TensorboardRoot"}, "--max_epochs",
          {"inputValue": "MaxEpochs"}, "--gpus", {"inputValue": "Gpus"}, "--train_batch_size",
          {"inputValue": "TrainBatchSize"}, "--val_batch_size", {"inputValue": "ValBatchSize"},
          "--train_num_workers", {"inputValue": "TrainNumWorkers"}, "--val_num_workers",
          {"inputValue": "ValNumWorkers"}, "--learning_rate", {"inputValue": "LearningRate"},
          "--accelerator", {"inputValue": "Accelerator"}], "command": ["python", "/component/entry_point.py"],
          "image": "jagadeeshj/training_step:22-02-2021-12-23-59.762171"}}, "inputs":
          [{"description": "Path to the training data", "name": "TrainingData", "type":
          "String"}, {"description": "Maximum number of epochs", "name": "MaxEpochs",
          "type": "Integer"}, {"description": "Training batch size", "name": "TrainBatchSize",
          "type": "Integer"}, {"description": "Validation batch size", "name": "ValBatchSize",
          "type": "Integer"}, {"description": "Number of training workers", "name":
          "TrainNumWorkers", "type": "Integer"}, {"description": "Number of validation
          workers", "name": "ValNumWorkers", "type": "Integer"}, {"description": "Learning
          rate", "name": "LearningRate", "type": "Float"}, {"description": "Number
          of gpus", "name": "Gpus", "type": "Integer"}, {"description": "Accelerator
          for multi gpu setting", "name": "Accelerator", "type": "String"}], "name":
          "train_pytorch_cnn", "outputs": [{"description": "Path for the resulting
          model checkpoint", "name": "ModelCheckpoint", "type": "String"}, {"description":
          "Path for the tensorboard logs", "name": "TensorboardRoot", "type": "String"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "e0289bc55b6194760c4f71062b525f1c603a1493757f08f247f2d303105dff4b",
          "url": "training_step/resnet/component.yaml"}', pipelines.kubeflow.org/arguments.parameters: '{"Accelerator":
          "None", "Gpus": "1", "LearningRate": "0.001", "MaxEpochs": "1", "TrainBatchSize":
          "None", "TrainNumWorkers": "4", "ValBatchSize": "None", "ValNumWorkers":
          "4"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
